# Generated by Django 5.1.4 on 2024-12-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='owern',
            new_name='owner',
        ),
    ]
